version: 2.1
orbs:
  onboarding-orb: logan/onboarding-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.0
  node: circleci/node@5.0.3

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - onboarding-orb/greet
  python-install-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - onboarding-orb/install_python
  node-install-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - onboarding-orb/install_node
  testing:
    docker:
      - image: cimg/base:current
    steps:
      - onboarding-orb/echo
    
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - python-install-test:
          filters: *filters
      - node-install-test:
          filters: *filters
      - testing:
          filters: *filters
      - onboarding-orb/hello:
          filters: *filters
      - onboarding-orb/hello_default:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: logan/onboarding-orb
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-tests
            - python-install-test
            - node-install-test
            - onboarding-orb/hello
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
